feat: 헤더 퍼블리싱 & 간단한 기능 구현
pa-rang/kyrics-frontend pull request #8
Opened 2021-07-08 15:29 UTC by Daeun-Danna-Lee

## ✅ PR check list

- [x] PR 제목: [feat/fix/refactor...] 작업 내용 한 줄 요약 (브랜치 이름) 
- [ ] commit message가 적절한지 확인해주세요.  
- [ ] 적절한 branch로 요청했는지 확인해주세요.  
- [ ] Assignees, Label을 붙여주세요.  
- [ ] 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer로 등록해주세요.
- [ ] PR이 승인된 경우 해당 브랜치는 삭제 부탁드립니다.  

<br/>

## 📝 PR 요약

- 헤더 퍼블리싱 
- 헤더 로고 클릭하면 홈으로 돌아오는 기능 구현
- 로그인/로그아웃 상태에서의 다른 헤더 구현
- 로그인 했을 때 프로필 누르면 뜨는 팝업 구현

<br/>

## 📸 ScreenShot

**로그아웃 상태**
<img src="https://user-images.githubusercontent.com/71601985/124947499-d7f08d00-e04a-11eb-9db1-66648ca15b0a.png" width=80% />

<br/>

**로그인 상태**
<img src="https://user-images.githubusercontent.com/71601985/124949238-58fc5400-e04c-11eb-8f79-ed4590915f88.png" width=80% />

<br/>

**로그인 상태 - 프로필 클릭**
<img src="https://user-images.githubusercontent.com/71601985/124949528-9b259580-e04c-11eb-9256-f26bdffeb695.png" width=80% />

2021-07-08 15:30 UTC, Daeun-Danna-Lee commented on components/common/Header.tsx
> +            </div>
로그인 상태인 경우 뜨는 것들

2021-07-08 15:30 UTC, Daeun-Danna-Lee commented on components/common/Header.tsx
> +        </div>
로그아웃 상태에서 뜨는 것들

2021-07-08 15:31 UTC, Daeun-Danna-Lee commented on components/common/ProfileHover.tsx
> +  right: 58px;
프로필 누르면 나오는 팝업 위치를 어떻게 해야 될지 모르겠어서 일단 고정값으로 위치는 줬는데 더 좋은 방법이 있을까?

2021-07-08 15:32 UTC, Daeun-Danna-Lee commented on components/common/Header.tsx
> +function Header({ isLoggedIn = false }: HeaderProps): ReactElement {
로그인 상태는 props로 받고 있어

2021-07-09 00:56 UTC, euijinkk requested changes

2021-07-09 00:56 UTC, euijinkk commented on components/common/Header.tsx
> +    setIsProfileClicked(!isProfileClicked);
이코드 좋다 ㅎㅎ !로 쓰면 되구나.. 항상 분기처리했는데 ㅋㅋ

2021-07-09 00:56 UTC, euijinkk commented on components/common/Header.tsx
> +                  alt=""
alt 안 넣어줘도 에러 안뜨넹? jsx-a11y 가 작동하지 않는건가..

2021-07-09 00:56 UTC, euijinkk commented on components/common/ProfileHover.tsx
> +  right: 58px;
headerWrap이나 header나 user나 userProfile 중 하나를 position:relative로 만들고, 그 안에 ProfileHover를 넣고 position:absolute 주고 스타일링하면 될것같음!!

2021-07-09 00:56 UTC, euijinkk commented on components/common/ProfileHover.tsx
> +  /* justify-content: space-around; */
주석 필요없으면 지워주세욥~

2021-07-09 00:56 UTC, euijinkk commented
코드 깔끔합니당~~~ 굿굿

2021-07-09 01:49 UTC, pa-rang commented on components/common/Header.tsx
> +                  alt=""
빈 alt 태그 넣어주면 에러 안뜸~

2021-07-09 01:53 UTC, pa-rang commented on components/common/Header.tsx
> +    setIsProfileClicked(!isProfileClicked);
prevState 기반으로 새 state를 정의할 때는 callback으로 이전 상태를 보장해주는 것이 좋아!

```suggestion
  function handleProfileClick(e: React.MouseEvent<HTMLButtonElement, MouseEvent>) {
    e.preventDefault();
    setIsProfileClicked(isProfileClicked => !isProfileClicked);
```

2021-07-09 01:55 UTC, pa-rang commented on components/common/Header.tsx
> +    setIsProfileClicked(!isProfileClicked);
참고로 Suggestion은 `Commit suggestion` 누르면 바로 해당 사항 변경해서 커밋할 수 있음~~ 꿀팁입니다👍

2021-07-09 02:47 UTC, euijinkk commented on components/common/Header.tsx
> +    setIsProfileClicked(!isProfileClicked);
와웅... 짱이다

2021-07-09 02:47 UTC, euijinkk commented on components/common/Header.tsx
> +                  alt=""
짱입니다!

2021-07-09 04:37 UTC, Daeun-Danna-Lee commented on components/common/Header.tsx
> +    setIsProfileClicked(!isProfileClicked);
우왕 그렇구만 감사합니당~~

2021-07-09 04:41 UTC, Daeun-Danna-Lee commented on components/common/ProfileHover.tsx
> +  /* justify-content: space-around; */
오홍 발견을 못했네 바로 반영하겠습니닷

2021-07-09 04:49 UTC, pa-rang commented on components/common/Header.tsx
> +function Header({ isLoggedIn = false }: HeaderProps): ReactElement {
사실 로그인 상태는 Header 내부에서 처리하는게 좋을 것 같긴해! 근데 로그인 쪽은 개발이 아직이니까 추후에 반영하면 좋을 것 같아여~

2021-07-09 04:51 UTC, pa-rang commented on components/common/ProfileHover.tsx
> +function ProfileHover(): ReactElement {
`ProfileHover`보다 `ProfileMenu`와 같은 이름이 좀 더 직관적이지 않을까여??

2021-07-09 04:55 UTC, Daeun-Danna-Lee commented on components/common/ProfileHover.tsx
> +function ProfileHover(): ReactElement {
마자 .. 사실 호버하면 나타나는 앤 줄 알고 이름 그렇게 지었다가 아니어서 바꿔야지 했는데 사실 귀찮아서 안 바꿨어 .. 바꿀게 🥲

2021-07-09 04:55 UTC, pa-rang commented on components/common/ProfileHover.tsx
> +      </button>
아래처럼 반복을 줄여보는건 어떨까!!

```javascript
const menuItems = ["Account Settings", "My songs", "My voca"]

{menuItems.map((item) => (
  <MenuItem 
    title 
    icon 
    handleClick 
  />
))}
```

2021-07-09 04:56 UTC, Daeun-Danna-Lee commented on components/common/ProfileHover.tsx
> +      </button>
오 좋다 사실 이거도 물어보려 했었는데 까먹었네 반영하겠습니다 ~~!~!

2021-07-09 05:04 UTC, Daeun-Danna-Lee commented on components/common/ProfileHover.tsx
> +  /* justify-content: space-around; */
반영 완료~! (91b03bf)

2021-07-09 05:39 UTC, Daeun-Danna-Lee commented on components/common/ProfileHover.tsx
> +function ProfileHover(): ReactElement {
수정 완료~! (e3ccb6e)

2021-07-09 06:22 UTC, euijinkk approved these changes
request changes -> approve 어케 바꾸징~

2021-07-09 06:26 UTC, Nahee-Park approved these changes
크 고생했어 깔끔하다!💜

2021-07-09 16:58 UTC, Daeun-Danna-Lee commented on components/common/ProfileHover.tsx
> +      </button>
이거 첫번째 두번째에만 있는 보더 때문에 고려해야 할 게 꽤 복잡해서 일단 홈이랑 카테고리 만들고 리팩토링 해볼게~!

2021-07-09 17:23 UTC, Daeun-Danna-Lee commented on components/common/ProfileHover.tsx
> +  right: 58px;
덕분에 수정 완료!!! (cf19c63)

2021-07-09 17:24 UTC, Daeun-Danna-Lee commented on components/common/Header.tsx
> +function Header({ isLoggedIn = false }: HeaderProps): ReactElement {
맞아 안 그래도 로그아웃이나 이런 거 처리 어떻게 해야할지 고민하고 있었다!!

2021-07-09 17:31 UTC, merged